# Generated by Django 6.0.3 on 2026-05-25 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('staff_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Laboratory', 'Laboratory'), ('Administrative', 'Administrative'), ('Clerical', 'Clerical')], max_length=20)),
                ('department', models.CharField(default='Forensic Medicine', max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('nmc_number', models.CharField(max_length=20, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('jmo_type', models.CharField(choices=[('Consultant JMO', 'Consultant JMO'), ('Senior JMO', 'Senior JMO'), ('Junior JMO', 'Junior JMO')], max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(default='Forensic Medicine', max_length=100)),
                ('office_contact_no', models.CharField(blank=True, max_length=15)),
                ('signature_path', models.ImageField(blank=True, null=True, upload_to='doctors/signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to='staff.staff')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
