# Generated by Django 4.2.30 on 2026-07-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Forensic Medicine', 'Forensic Medicine'), ('Castle Street Hospital for Children', 'Castle Street Hospital for Children'), ('National Hospital of Sri Lanka', 'National Hospital of Sri Lanka'), ('Eye and ENT Hospital, Ragama', 'Eye and ENT Hospital, Ragama'), ('Lady Ridgeway Hospital for Children', 'Lady Ridgeway Hospital for Children'), ('District General Hospital - Gampaha', 'District General Hospital - Gampaha'), ('District General Hospital - Kalutara', 'District General Hospital - Kalutara')], max_length=100),
        ),
    ]
