# Generated by Django 6.0.3 on 2026-05-25 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postmortem',
            fields=[
                ('postmortem_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('inquest_order_date', models.DateField(blank=True, null=True)),
                ('court_order_date', models.DateField(blank=True, null=True)),
                ('autopsy_date', models.DateTimeField()),
                ('autopsy_start_time', models.TimeField(blank=True, null=True)),
                ('autopsy_end_time', models.TimeField(blank=True, null=True)),
                ('autopsy_location', models.CharField(blank=True, max_length=300)),
                ('inquest_number', models.CharField(blank=True, max_length=50)),
                ('court_order_number', models.CharField(blank=True, max_length=50)),
                ('external_findings', models.TextField(blank=True)),
                ('internal_findings', models.TextField(blank=True)),
                ('organ_findings', models.TextField(blank=True)),
                ('immediate_cause', models.CharField(blank=True, max_length=300, verbose_name='Immediate Cause of Death')),
                ('cause_a', models.CharField(blank=True, max_length=300, verbose_name='Cause A (Due to)')),
                ('cause_b', models.CharField(blank=True, max_length=300, verbose_name='Cause B (Due to)')),
                ('cause_c', models.CharField(blank=True, max_length=300, verbose_name='Cause C (Due to)')),
                ('death_type', models.CharField(choices=[('Natural', 'Natural'), ('Accidental', 'Accidental'), ('Suicidal', 'Suicidal'), ('Homicidal', 'Homicidal'), ('Undetermined', 'Undetermined')], max_length=20)),
                ('estimated_time_of_death', models.DateTimeField(blank=True, null=True)),
                ('audio_recording_path', models.CharField(blank=True, max_length=500)),
                ('audio_duration_secs', models.PositiveIntegerField(blank=True, null=True)),
                ('photographs_taken', models.PositiveSmallIntegerField(default=0)),
                ('photograph_path', models.CharField(blank=True, max_length=500)),
                ('specimen_collected', models.BooleanField(default=False)),
                ('specimen_details', models.TextField(blank=True)),
                ('assistant_names', models.CharField(blank=True, max_length=500)),
                ('report_status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='postmortem', to='cases.forensiccase')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postmortems', to='staff.doctor')),
            ],
            options={
                'verbose_name': 'Postmortem',
                'ordering': ['-autopsy_date'],
            },
        ),
    ]
