# Generated by Django 4.2.30 on 2026-07-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmortem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortuary',
            fields=[
                ('mortuary_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Max number of bodies')),
                ('current_occupancy', models.PositiveSmallIntegerField(default=0)),
                ('refrigeration', models.BooleanField(default=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Under Maintenance'), ('Closed', 'Closed')], default='Available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mortuary',
                'verbose_name_plural': 'Mortuaries',
                'ordering': ['room_number'],
            },
        ),
    ]
