# Generated by Django 6.0.3 on 2026-05-25 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('evidence_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('evidence_type', models.CharField(max_length=100)),
                ('evidence_description', models.TextField(blank=True)),
                ('collection_date', models.DateTimeField()),
                ('collected_by', models.CharField(blank=True, max_length=100)),
                ('storage_location', models.CharField(blank=True, max_length=300)),
                ('storage_temperature', models.CharField(blank=True, max_length=50)),
                ('storage_conditions', models.CharField(blank=True, max_length=300)),
                ('barcode_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('qr_code_data', models.CharField(blank=True, max_length=500)),
                ('chain_of_custody', models.TextField(blank=True)),
                ('last_handled_by', models.CharField(blank=True, max_length=100)),
                ('last_handled_date', models.DateTimeField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Disputed', 'Disputed')], default='Pending', max_length=20)),
                ('analysis_type', models.CharField(blank=True, max_length=200)),
                ('analysis_result', models.TextField(blank=True)),
                ('disposal_status', models.CharField(choices=[('Stored', 'Stored'), ('ReturnedToPolice', 'Returned to Police'), ('Destroyed', 'Destroyed'), ('Unknown', 'Unknown')], default='Stored', max_length=25)),
                ('disposal_date', models.DateTimeField(blank=True, null=True)),
                ('disposal_approved_by', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='cases.forensiccase')),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('test_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=100)),
                ('test_description', models.CharField(blank=True, max_length=300)),
                ('requested_date', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=100)),
                ('test_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.TextField(blank=True)),
                ('result_interpretation', models.TextField(blank=True)),
                ('test_status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('OnHold', 'On Hold')], default='Pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('test_notes', models.TextField(blank=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_path', models.CharField(blank=True, max_length=500)),
                ('report_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='evidence.evidence')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Laboratory Test',
                'ordering': ['-test_date'],
            },
        ),
    ]
