# Generated by Django 4.2.30 on 2026-07-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_doctor_department'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceChainOfCustody',
            fields=[
                ('custody_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('Collected', 'Collected'), ('Transferred', 'Transferred'), ('Analysed', 'Analysed'), ('Stored', 'Stored'), ('Returned', 'Returned to Police'), ('Disposed', 'Disposed'), ('Inspected', 'Inspected')], max_length=20)),
                ('handled_by', models.CharField(max_length=100)),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(blank=True, max_length=200)),
                ('action_datetime', models.DateTimeField()),
                ('purpose', models.CharField(blank=True, max_length=300)),
                ('condition_note', models.CharField(blank=True, help_text='Condition of evidence at time of handling', max_length=300)),
                ('signature_obtained', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_records', to='evidence.evidence')),
                ('handled_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_records', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Evidence Chain of Custody',
                'verbose_name_plural': 'Evidence Chain of Custody Records',
                'ordering': ['-action_datetime'],
            },
        ),
    ]
