# Generated by Django 6.0.3 on 2026-05-25 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicCase',
            fields=[
                ('case_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('case_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('case_type', models.CharField(choices=[('Clinical Forensic', 'Clinical Forensic'), ('Autopsy', 'Autopsy'), ('Clinical & Autopsy', 'Clinical & Autopsy')], max_length=30)),
                ('incident_date', models.DateTimeField()),
                ('incident_location', models.CharField(blank=True, max_length=300)),
                ('incident_type', models.CharField(blank=True, max_length=100)),
                ('police_report_no', models.CharField(blank=True, max_length=50)),
                ('court_case_no', models.CharField(blank=True, max_length=50)),
                ('case_status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Submitted', 'Submitted'), ('Closed', 'Closed'), ('Archived', 'Archived')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10)),
                ('case_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='staff.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Forensic Case',
                'ordering': ['-created_at'],
            },
        ),
    ]
