# Generated by Django 4.2.30 on 2026-07-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WitnessStatement',
            fields=[
                ('statement_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('witness_name', models.CharField(max_length=100)),
                ('witness_nic', models.CharField(blank=True, max_length=20, verbose_name='NIC / ID Number')),
                ('witness_contact', models.CharField(blank=True, max_length=15)),
                ('witness_address', models.TextField(blank=True)),
                ('relationship_to_case', models.CharField(blank=True, help_text='e.g. Eyewitness, Relative, Police Officer', max_length=100)),
                ('statement_type', models.CharField(choices=[('Verbal', 'Verbal'), ('Written', 'Written'), ('Recorded', 'Audio/Video Recorded')], default='Written', max_length=20)),
                ('statement_text', models.TextField()),
                ('statement_date', models.DateTimeField()),
                ('recorded_by', models.CharField(blank=True, max_length=100)),
                ('recording_path', models.CharField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='witness_statements', to='cases.forensiccase')),
            ],
            options={
                'verbose_name': 'Witness Statement',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('note_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('note_type', models.CharField(choices=[('General', 'General'), ('Medical', 'Medical'), ('Legal', 'Legal'), ('FollowUp', 'Follow-Up'), ('Internal', 'Internal')], default='General', max_length=20)),
                ('note_text', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Private notes are only visible to doctors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.forensiccase')),
            ],
            options={
                'verbose_name': 'Case Note',
                'ordering': ['-created_at'],
            },
        ),
    ]
