# Generated by Django 6.0.3 on 2026-05-25 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('SUBMIT', 'Submit'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock')], max_length=10)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=30)),
                ('action_details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['user', 'logged_at'], name='core_activi_user_id_a092be_idx'), models.Index(fields=['action_type'], name='core_activi_action__ba020b_idx'), models.Index(fields=['model_name'], name='core_activi_model_n_8de83f_idx')],
            },
        ),
    ]
