# Generated by Django 6.0.3 on 2026-05-25 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalExamination',
            fields=[
                ('exam_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('examination_date', models.DateTimeField()),
                ('examination_type', models.CharField(blank=True, max_length=100)),
                ('time_of_examination', models.TimeField(blank=True, null=True)),
                ('general_condition', models.CharField(blank=True, max_length=200)),
                ('consciousness', models.CharField(blank=True, choices=[('Alert', 'Alert'), ('Confused', 'Confused'), ('Drowsy', 'Drowsy'), ('Unconscious', 'Unconscious'), ('Unknown', 'Unknown')], max_length=20)),
                ('nutritional_status', models.CharField(blank=True, max_length=100)),
                ('photographs_taken', models.PositiveSmallIntegerField(default=0)),
                ('photograph_path', models.CharField(blank=True, max_length=500)),
                ('injury_details', models.TextField(blank=True)),
                ('wound_description', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('causative_weapon', models.CharField(blank=True, max_length=100)),
                ('investigation_required', models.BooleanField(default=False)),
                ('investigation_type', models.CharField(blank=True, max_length=200)),
                ('referral_required', models.BooleanField(default=False)),
                ('referral_department', models.CharField(blank=True, max_length=100)),
                ('referral_reason', models.CharField(blank=True, max_length=300)),
                ('officer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_examinations', to='cases.forensiccase')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_examinations', to='staff.doctor')),
            ],
            options={
                'verbose_name': 'Clinical Examination',
                'ordering': ['-examination_date'],
            },
        ),
    ]
