# Generated by Django 4.2.30 on 2026-07-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_witnessstatement_casenote'),
        ('staff', '0002_alter_doctor_department'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(choices=[('ClinicalExam', 'Clinical Examination'), ('FollowUp', 'Follow-Up'), ('CourtAppearance', 'Court Appearance'), ('Consultation', 'Consultation')], default='ClinicalExam', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('NoShow', 'No Show')], default='Scheduled', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='cases.forensiccase')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='staff.doctor')),
            ],
            options={
                'verbose_name': 'Appointment',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
