# Generated by Django 6.0.3 on 2026-05-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('nic_passport', models.CharField(max_length=20, unique=True, verbose_name='NIC / Passport')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Unknown', 'Unknown')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('contact_no', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_no', models.CharField(blank=True, max_length=15)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='patients/photos/')),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Unknown', 'Unknown')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
