# Generated by Django 6.0.3 on 2026-05-25 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtReport',
            fields=[
                ('report_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('MLR', 'MLR — Medico-Legal Report'), ('PMR', 'PMR — Postmortem Report'), ('Combined', 'Combined (MLR + PMR)')], max_length=10)),
                ('report_title', models.CharField(blank=True, max_length=300)),
                ('report_content', models.TextField(blank=True)),
                ('report_conclusions', models.TextField(blank=True)),
                ('recommended_investigations', models.TextField(blank=True)),
                ('court_name', models.CharField(blank=True, max_length=300)),
                ('court_case_number', models.CharField(blank=True, max_length=50)),
                ('magistrate_district', models.CharField(blank=True, max_length=100)),
                ('judge_name', models.CharField(blank=True, max_length=100)),
                ('lawyer_details', models.CharField(blank=True, max_length=300)),
                ('report_status', models.CharField(choices=[('Draft', 'Draft'), ('Generated', 'Generated'), ('Reviewed', 'Reviewed'), ('Submitted', 'Submitted'), ('Received', 'Received'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('submission_proof_path', models.CharField(blank=True, max_length=500)),
                ('digital_signature_path', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='court_reports', to='cases.forensiccase')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='court_reports', to='staff.doctor')),
            ],
            options={
                'verbose_name': 'Court Report',
                'ordering': ['-generated_at'],
            },
        ),
    ]
